title: Arriqaaq
description: >-
  An online creative space for authentic islamic courses, articles, crafts,
  education and technology
logo: /images/2021/04/Arriqaaq-1.png
icon: /images/2021/04/Flower-Fern-Business-logo-2.png
cover_image: https://static.ghost.org/v4.0.0/images/publication-cover.jpg
navigation:
  - url: /
    label: Home
    mobile: true
  - url: /courses/
    label: Courses
  - url: /magazine/
    label: Magazine
    mobile: true
  - url: https://www.instagram.com/arriqaaq/
    label: Instagram
    mobile: true
  - url: https://chat.whatsapp.com/G9uGLfu3mwCJrvN5KqNDJ7
    label: WhatsApp
    mobile: true
  - url: /about/
    label: About
    mobile: true
  - url: /lettersfromthesoul/
    label: Letters From The Soul
    mobile: true
  - url: https://health.arriqaaq.com/
    label: Health
  - url: https://github.com/arriqaaq
    label: Tech
    mobile: true
secondary_navigation:
  - label: Data & privacy
    url: /privacy/
  - label: Contact
    url: /contact/
